SELECT * FROM TRANSFERS;

--  JUGADOR MÁS JOVEN POR PAÍS Y JUGADOR MÁS VETERANO POR PAÍS

SELECT COUNTRY_PLAYING_IN, MAX(PLAYER_AGE), MIN(PLAYER_AGE)
FROM TRANSFERS 
GROUP BY COUNTRY_PLAYING_IN
ORDER BY COUNTRY_PLAYING_IN;


-- EDAD MEDIA DE LOS JUGADORES QUE VALEN MAS DE 100 MILLONES

SELECT PLAYER_NAME, PLAYER_AGE,PLAYER_MARKET_VALUE_M
FROM TRANSFERS
WHERE PLAYER_MARKET_VALUE_M > 100;

-- JUGADORES TRANSFERIDOS POR POSCICION A LA PREMIER LEAGUE EN INGLATERRA Y LA LIGA DE ESPAÑA

SELECT PLAYER_POSITION, COUNT(PLAYER_POSITION) AS CANTIDAD 
FROM TRANSFERS
WHERE NEW_LEAGUE IN ('PREMIER LEAGUE','LALIGA') 
GROUP BY PLAYER_POSITION
HAVING COUNT(PLAYER_POSITION)
ORDER BY CANTIDAD DESC;

-- CREA UN RANKING DE LOS JUGADORES MEJORES PAGOS (TRANSFERENCIA) POR POSICIÓN EN EL CONJUNTO DE DATOS Y DAME EL TOP 3 POR POSICION


WITH RANKED AS (
SELECT PLAYER_NAME,PLAYER_POSITION, FEES_PAID_FOR_PLAYER_M,
DENSE_RANK() OVER(PARTITION BY PLAYER_POSITION   ORDER BY FEES_PAID_FOR_PLAYER_M  DESC) AS RANK_PLAYER
FROM TRANSFERS
)
SELECT PLAYER_NAME,PLAYER_POSITION, RANK_PLAYER, FEES_PAID_FOR_PLAYER_M
FROM RANKED
WHERE RANK_PLAYER IN (1,2,3)
ORDER BY PLAYER_POSITION;

-- ¿QUÉ CLUBES DE LA PREMIER LEAGUE HAN FICHADO NUEVOS JUGADORES SEGÚN EL CONJUNTO DE DATOS Y CUANTOS?


SELECT   CLUB_MOVING_TO, COUNT( *)
FROM TRANSFERS
WHERE NEW_LEAGUE  = 'PREMIER LEAGUE' AND ON_LOAN = 'NO'
GROUP BY  CLUB_MOVING_TO
ORDER BY  CLUB_MOVING_TO ASC;


-- ¿CUÁNTOS JUGADORES SON MENORES DE 18 AÑOS Y EN QUÉ PAÍS ESTARÁN JUGANDO?

SELECT  COUNT(PLAYER_NAME), COUNTRY_PLAYING_IN
FROM TRANSFERS 
WHERE PLAYER_AGE <18 
GROUP BY COUNTRY_PLAYING_IN
HAVING COUNT(PLAYER_NAME);


WITH RANKING AS  (
			SELECT PLAYER_NAME, COUNTRY_PLAYING_IN, PLAYER_AGE,
            DENSE_RANK() OVER(PARTITION BY COUNTRY_PLAYING_IN ORDER BY PLAYER_AGE) AS RANK_PLAYER
            FROM TRANSFERS
            )
SELECT  COUNTRY_PLAYING_IN, PLAYER_AGE, COUNT(COUNTRY_PLAYING_IN)
FROM RANKING
WHERE PLAYER_AGE < 18
GROUP BY COUNTRY_PLAYING_IN  ;

-- TOTAL PAGADO POR PAÍS EN TRANSFERENCIAS 

SELECT COUNTRY_MOVING_TO, SUM(FEES_PAID_FOR_PLAYER_M)  
FROM TRANSFERS 
GROUP BY COUNTRY_MOVING_TO
ORDER BY SUM(FEES_PAID_FOR_PLAYER_M) DESC;

-- POSICIÓN MÁS CARA DEL MERCADO

SELECT PLAYER_POSITION, PLAYER_MARKET_VALUE_M
FROM TRANSFERS
GROUP BY PLAYER_MARKET_VALUE_M
ORDER BY PLAYER_MARKET_VALUE_M DESC ;

-- POSICIÓN MÁS CARA DEL MERCADO:

SELECT  PLAYER_POSITION , PLAYER_MARKET_VALUE_M
FROM TRANSFERS
ORDER BY PLAYER_MARKET_VALUE_M DESC
LIMIT 1;

-- POSICIÓN POR LA CUAL SE PAGÓ MÁS DINERO EN LAS TRANSFERENCIAS:

SELECT  PLAYER_POSITION , FEES_PAID_FOR_PLAYER_M
FROM TRANSFERS
ORDER BY FEES_PAID_FOR_PLAYER_M DESC
LIMIT 1;

-- LOS 5 PAISES CON MAS CANTIDAD DE TRANSFERENCIAS DE LA TEMPORADA

SELECT COUNTRY_MOVING_TO , COUNT(*) AS COUNT_TRANSFER
FROM TRANSFERS
GROUP BY COUNTRY_MOVING_TO 
ORDER BY COUNT_TRANSFER DESC
LIMIT 5 ;

-- LOS 5 CLUBES CON MÁS CANTIDAD DE TRANSFERENCIAS DE LA TEMPORADA

SELECT CLUB_MOVING_TO , COUNT(*) AS COUNT_TRANSFER
FROM TRANSFERS
GROUP BY CLUB_MOVING_TO
ORDER BY COUNT_TRANSFER DESC
LIMIT 5;
 
-- LAS 5 LIGAS CON MÁS CANTIDAD DE TRANSFERENCIAS DE LA TEMPORADA

SELECT CLUB_MOVING_TO , COUNT(*) AS COUNT_TRANSFER
FROM TRANSFERS
GROUP BY CLUB_MOVING_TO 
ORDER BY COUNT_TRANSFER DESC
LIMIT 5;

-- PROMEDIO PAGADO POR POSICIÓN:

SELECT  PLAYER_POSITION , ROUND(AVG(FEES_PAID_FOR_PLAYER_M),2) AS PROMEDIO
FROM TRANSFERS
WHERE FEES_PAID_FOR_PLAYER_M  > 0
GROUP BY PLAYER_POSITION;

-- DIFERENCIA ENTRE VALOR DE MERCADO Y PAGADO EN TRANSFERENCIAS:

SELECT PLAYER_NAME, PLAYER_POSITION, PLAYER_MARKET_VALUE_M,  FEES_PAID_FOR_PLAYER_M,
(FEES_PAID_FOR_PLAYER_M - PLAYER_MARKET_VALUE_M)  AS DIFERENCIA 
FROM TRANSFERS
WHERE FEES_PAID_FOR_PLAYER_M  > 0;

-- EL CLUB QUE GASTÓ MÁS DINERO EN LAS TRANSFERENCIAS ESTA TEMPORADA

SELECT  CLUB_MOVING_TO , SUM(FEES_PAID_FOR_PLAYER_M) AS PAID
FROM TRANSFERS
WHERE  ON_LOAN = 'NO'
GROUP BY CLUB_MOVING_TO 
ORDER BY PAID DESC
LIMIT 1;
 

-- EL PAÍS QUE GASTÓ MÁS DINERO EN LAS TRANSFERENCIAS ESTA TEMPORADA

SELECT  COUNTRY_MOVING_TO , SUM("FEES PAID FOR PLAYER (M)") AS PAID
FROM TRANSFERS
WHERE  ON_LOAN = 'NO'
GROUP BY COUNTRY_MOVING_TO 
ORDER BY PAID DESC;


-- LA LIGA QUE GASTÓ MÁS DINERO EN LAS TRANSFERENCIAS ESTA TEMPORADA

SELECT  COUNTRY_MOVING_TO , SUM(FEES_PAID_FOR_PLAYER_M) AS PAID
FROM TRANSFERS
WHERE  ON_LOAN = 'NO'
GROUP BY COUNTRY_MOVING_TO
ORDER BY PAID DESC
LIMIT 1;